platform :ios, '13.0'

flutter_application_path = '..'

# Sửa lỗi: Dùng File.exist? (không có chữ s) đúng chuẩn Ruby mới
if File.exist?(File.join(flutter_application_path, '.symlinks', 'plugins', 'flutter_plugin_loader', 'ios', 'PluginLoader.rb'))
  load File.join(flutter_application_path, '.symlinks', 'plugins', 'flutter_plugin_loader', 'ios', 'PluginLoader.rb')
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  if File.exist?(File.join(flutter_application_path, '.ios', 'Flutter'))
    pod 'Flutter', :path => File.join(flutter_application_path, '.ios', 'Flutter')
  elsif File.exist?(File.join(flutter_application_path, 'Flutter'))
    pod 'Flutter', :path => File.join(flutter_application_path, 'Flutter')
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end