name: Build iOS IPA Unsigned

on:
  push:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Pre-build iOS to Generate Podfile
        run: |
          flutter pub get
          # Bước cốt lõi: Ép Flutter tự sinh cấu trúc thư mục ios native và tạo file Podfile chuẩn
          flutter build ios --config-only

      - name: Install Pod Dependencies
        run: |
          cd ios
          pod repo update
          pod install

      - name: Build iOS Application (No Sign)
        run: |
          flutter build ios --release --no-codesign --obfuscate --split-debug-info=build/ios/outputs/symbols

      - name: Pack App into IPA Archive
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r ios-app-test.ipa Payload

      - name: Upload IPA Product to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: iphone-app-test
          path: ios-app-test.ipa